#spring:
#  application:
#    name: demo-dubbo-exception-provider



server:
  port: 8002

dubbo:
  application:
    name: demo-dubbo-exception-provider
  registry:
    address: N/A
  scan:
    base-packages: com.yx.demo.dubbo.exception.provider.api.impl
  protocol:
    name: dubbo
    port: 28002
  provider:
    filter: customerExceptionFilter
